# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: calendar_date_select 1.17.0 ruby lib

Gem::Specification.new do |s|
  s.name = "calendar_date_select".freeze
  s.version = "1.17.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Shih-gian Lee".freeze, "Enrique Garcia Cota (kikito)".freeze, "Tim Charper".freeze, "Lars E. Hoeg".freeze, "Andrew Hodgkinson".freeze]
  s.date = "2017-08-13"
  s.description = "Calendar date picker for Rails 4".freeze
  s.email = "".freeze
  s.extra_rdoc_files = [
    "README.txt"
  ]
  s.files = [
    "History.txt",
    "MIT-LICENSE",
    "Manifest.txt",
    "README.txt",
    "Rakefile",
    "VERSION",
    "calendar_date_select.gemspec",
    "js_test/functional/.tmp_cds_test.html",
    "js_test/functional/cds_test.html",
    "js_test/functional/format_iso_date_test.html",
    "js_test/prototype.js",
    "js_test/test.css",
    "js_test/unit/cds_helper_methods.html",
    "js_test/unittest.js",
    "lib/calendar_date_select.rb",
    "lib/calendar_date_select/calendar_date_select.rb",
    "lib/calendar_date_select/form_helpers.rb",
    "lib/calendar_date_select/includes_helper.rb",
    "public/blank_iframe.html",
    "public/images/calendar_date_select/calendar.gif",
    "public/javascripts/calendar_date_select/calendar_date_select.js",
    "public/javascripts/calendar_date_select/format_american.js",
    "public/javascripts/calendar_date_select/format_danish.js",
    "public/javascripts/calendar_date_select/format_db.js",
    "public/javascripts/calendar_date_select/format_euro_24hr.js",
    "public/javascripts/calendar_date_select/format_euro_24hr_ymd.js",
    "public/javascripts/calendar_date_select/format_finnish.js",
    "public/javascripts/calendar_date_select/format_hyphen_ampm.js",
    "public/javascripts/calendar_date_select/format_iso_date.js",
    "public/javascripts/calendar_date_select/format_italian.js",
    "public/javascripts/calendar_date_select/locale/ar.js",
    "public/javascripts/calendar_date_select/locale/cs.js",
    "public/javascripts/calendar_date_select/locale/da.js",
    "public/javascripts/calendar_date_select/locale/de.js",
    "public/javascripts/calendar_date_select/locale/es.js",
    "public/javascripts/calendar_date_select/locale/fi.js",
    "public/javascripts/calendar_date_select/locale/fr.js",
    "public/javascripts/calendar_date_select/locale/it.js",
    "public/javascripts/calendar_date_select/locale/ja.js",
    "public/javascripts/calendar_date_select/locale/nl.js",
    "public/javascripts/calendar_date_select/locale/pl.js",
    "public/javascripts/calendar_date_select/locale/pt.js",
    "public/javascripts/calendar_date_select/locale/ru.js",
    "public/javascripts/calendar_date_select/locale/sl.js",
    "public/javascripts/calendar_date_select/locale/sv.js",
    "public/stylesheets/calendar_date_select/blue.css",
    "public/stylesheets/calendar_date_select/default.css",
    "public/stylesheets/calendar_date_select/green.css",
    "public/stylesheets/calendar_date_select/plain.css",
    "public/stylesheets/calendar_date_select/red.css",
    "public/stylesheets/calendar_date_select/silver.css",
    "spec/calendar_date_select/calendar_date_select_spec.rb",
    "spec/calendar_date_select/form_helpers_spec.rb",
    "spec/calendar_date_select/includes_helper_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/timcharper/calendar_date_select".freeze
  s.rubygems_version = "2.6.8".freeze
  s.summary = "Calendar date picker for Rails 4".freeze
end

